#index:
#    path: /
#    controller: App\Controller\DefaultController::index


find_by_food:
  path: /find/{food}/{page}/{perPage}
  controller: App\Controller\ApiController::find
  defaults:
    food: ""
    page: 1
    perPage: 25

details:
  path: /details/{food}/{page}/{perPage}
  controller: App\Controller\ApiController::details
  defaults:
    food: ""
    page: 1
    perPage: 25
